name: CI/CD Status App
on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repository
        uses: docker/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Setup Docker Buildx
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{vars.DOCKER_USERNAME}}/status-api:latest
                ${{ secrets.DOCKER_USERNAME }}/status-api:${{ github.sha }}
